### ISSUE TITLE
Adding a custom filter

### ISSUE THREAD

**Issue by danielbwa** [fortytools/forty_facets#12]
Thanks for this gem, looks really useful!

I'm looking at adding a custom method which is provided in the model i want to filter on, in this case the **near** method provided by the [geocoder](http://www.rubygeocoder.com/) gem. It would be nice to be able to include a way to filter the records by a method on the provided model.

Any ideas on how to deal with this?

Thanks again for your work!

**Comment by axelerator** [comment]
Sorry saw you question just now:

You can use the custom filter and the ability of the search to set a 'base-collection' like so:

https://gist.github.com/axelerator/e512dd751b29ff6559efc277dc5c00df

**Comment by danielbwa** [comment]
I'll give it a try, thanks!
