### ISSUE TITLE
How to turn off distinct.

### ISSUE THREAD

**Issue by Br3nda** [fortytools/forty_facets#21]
FortyFAcets seems to always put `DISTINCT` in the front of queries, however some column types can't be in a distinct.

```
PG::UndefinedFunction: ERROR:  could not identify an equality operator for type json
LINE 1: SELECT DISTINCT "variables".* FROM "variables"
```

Is there a way to tell the gem i don't want distinct there?

**Comment by Br3nda** [comment]
(other than added `.distinct(false)` everywhere)

**Comment by axelerator** [comment]
We never needed this, so currently there is no way to do that. Generally the distinct was introduced because we need it to correctly count results when joining with `has-many` relationships.
