### ISSUE TITLE
Range facet

### ISSUE THREAD

**Issue by Vanhecke** [fortytools/forty_facets#8]
The range facet doesn't seem to be working.
I set the value to eg "5 - 10" but it doesn't filter whatsoever.

The demo apps' price filter seems to be suffering from this as well.

**Comment by Vanhecke** [comment]
Nevermind, the I copied a different mistake from demo.
The input was set as `type="range"` which is an official html5 type and requires a slider with only 1 value.
Change it to eg `type="special_range"` and it works. I would like to fix the demo app but couldn't get `rake movies:import` to work.

**Comment by axelerator** [comment]
Thanks for the hint, I'm going to fix the demo..
