### ISSUE TITLE
Range filter does not work

### ISSUE THREAD

**Issue by rubykatz** [fortytools/forty_facets#9]
I've been trying to use a range filter with forty_facets, but it won't work. When I submit the form, the page is reloaded but the filter is thereby reset.

This is likely not an implementation error on my end because it can be reproduced in the demo implementation: http://forty-facets-demo.herokuapp.com/
(Choose any values in the slider and hit "Search" or press Enter.)

Reproduced in FF and Chromium.

**Comment by axelerator** [comment]
I'll look into it..

**Comment by axelerator** [comment]
The error is in fact a mistake in the app that I made in the demo as well.
The Problem is, that *disabled* input fields don't get submitted to the server.

See the fix I made in the demo:
https://github.com/fortytools/forty_facets_demo/commit/601e6354a825824ac42c0b66aa30579b220619ee
